spring:
  profiles:
    active: dev
  datasource:
    username: ${datasource.username}
    password: ${datasource.password}
    url: ${datasource.url}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: per.chowhound.hfut.domain
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
